private
page1source

	^'<html>
<head>
<title>Pharo-Chrome Test Page</title>
</head>
<body>
<h1>Title One</h1>
<p>Paragraph One</p>
<ul>
<li><a href="http://pharo.org">Go to Pharo.Org</a> with some more text</li>
</ul>

<h2>Test Tables</h2>

<table id="First Table">
<tr><th>Col 1</th><th>Col 2</th></tr>
<tr><td>Cell 11</td><td>Cell 21</td></tr>
<tr><td>Cell 12</td><td>Cell 22</td></tr>
</table>

<table>
<tr><th>Col 1</th><th>Col 2</th><th>Col 3</th></tr>
<tr><td>Cell 11</td><td>Cell 21</td></tr>
<tr><td>Cell 12</td><td>Cell 22</td><td>Cell 23</td></tr>
</table>

</body>
</html>'